import pandas as pd


configfile: "config/config.yaml"


samples = pd.read_csv("config/samples.csv", index_col=["protein", "folder"])
PROTEINS = samples.index.unique(level="protein").tolist()
FOLDERS = samples.index.unique(level="folder").tolist()

# cis K18Ac, trans K18Ac and cis + trans K18Ac compared against unmod
plip_types = ["cis", "trans", "all"]


# Load rules
include: "rules/plip_hh.smk"
include: "rules/plip_type_breakdown.smk"


rule all:
    input:
        plip_k18_hh_plots=[
            f"combined_plots/plip_hh/plip_k18_k18ac_{i}.png" for i in plip_types
        ],
        plip_k9_hh_plots=[
            f"combined_plots/plip_hh/plip_k9_k9me3_{i}.png" for i in plip_types
        ],
        plip_r17_hh_plots=[
            f"combined_plots/plip_hh/plip_r17_{i}.png" for i in plip_types
        ],
        plip_k18_breakdown_plots=[
            f"combined_plots/plip_breakdown/plip_k18_k18ac_{i}_breakdown.png"
            for i in plip_types
        ],
        plip_k9_breakdown_plots=[
            f"combined_plots/plip_breakdown/plip_k9_k9me3_{i}_breakdown.png"
            for i in plip_types
        ],
        plip_r17_breakdown_plots=[
            f"combined_plots/plip_breakdown/plip_r17_{i}_breakdown.png"
            for i in plip_types
        ],
